# Generated by Django 5.2.1 on 2025-06-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(default='0000', max_length=10),
            preserve_default=False,
        ),
    ]
