# Generated by Django 5.2.1 on 2025-06-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_address_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.CharField(max_length=255),
        ),
    ]
