# Generated by Django 5.2.1 on 2025-06-09 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_inventory'),
    ]

    operations = [
        migrations.RunSQL(""" 
            INSERT INTO store_collection(title)
            VALUES('collection1')
        """, """
            DELETE FROM store_collection
            WHERE title = 'collection1'
        """)
    ]
